travis:
  secure:
    BINSTAR_TOKEN: vqs6JFyDZp6GWRrG6XMaVWb+NP0fmhjZmdTqXzSpW2TKUmkzCOkuinWOH1deorP+rZBhlbYYxtY9RCeHBHTnZNU+X33ys+W2Kumf1l+nKQXUPZSXcbIbCbynAqEhEXdfDr4kuf6IYyaTGYhhxUKCrgDwnxcIglujLkeaKix+LI0bi2oWJz605tuPo4/0nEng8LHZ+3/YgACou/7WHTOUFG1xWogsNqxLlFWPxduk9+TvRf9zjczSL4duGfEnr7ES/hDG2QPyo7SYgv4EfuDhfYekNoUrf0Py9qBkTtkH3s8lP60EXo3Vj96tCf9WAcSU1O8tC87jZORxybd/wFX1epobeNdoabxVhxw+Y/7gIv7cKy0/OhVstlh2SUh018WNmpgwdBrw3CUQSTz2pCbEJF5L7RvqJ+hmE7+qOSm/s8ozpmV2XpPLC0Ao5ZWeb+vBxfLfY4V70kfTX64Js5iGJw2LHKk+HQXt7D0r9BrcxGxlmNEjdHHg+6KNOHLA+okOehHr0dAkLSkQfZo8f/9sIoywyHO0VVQF2DSwT0t5YYE7+a01XshebV6Qn/9oWSE8wQvcgyOTtOqMLv1Ff+KxLVxkbx6MyLnl2Sx7kSbBnIDAv6qW9op+fNSIfesTg912Kb7QuIYwWFUc+bcqHCLAX0YO3cU23Q+vLTIxvxW2Sqw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
