travis:
  secure:
    BINSTAR_TOKEN: hDkUZu26g22oIpAlFaqxOBMUBuzAiUGW6t6iKdn2K4XEK01zjuNbnqwDGFE9Kx4Fnuw4T94GojUZ+A6UkN55bHa/YaD5PvQiO/mamcLVl5/fBD/pBroShmGHdah8+U0+xoRxr1SusJJ9uNiHU2UfSOdObP6BMKNgX8aWZ4UFsVL+oMTVq3isJXAo3G496noR/1zLkc6UEOm9+QmAhWldZVH/Oww/AH6Ilri6p125kdtvx+6zaGyiG1lS+xPWgY61Ztn/Rq0E3VNAPcEg2rcveEGbctOJXvBTcGalv/F5+P8xbdyo5SzqOv9onYTgAqlt76nBy547C4OBnYjZVobKzywvPu7WiciFIE73TO1GREmPXU1ZpO9S3JZaAx1SWC0OPWPC8mrq+Qa0MRbInFA7i6YJVCk0+cWwgrDh4xcSzrL77OUxTUS+gpBHXHXSnXh94LULwxPQX/LMznahrFgVZwdPTvH8A1UXmRLohXJIrpK7hLfpXj2krHQohOsxlZHeFXImHN+hMAJMTdXxPWdoz4aLIiCmJWCnr4TmwDn3l9VZLNWGSDb+3dUVCrs0JFnCESj6jLPPsT9CxaDUBrJuIcferYkrmpN/pyqSgqN9+JTrwpF5kEPo37/x5C4XGg6992vnEu45jRFfJE/ARb2gP7usmSKGYQuKvSLT1PKuCYA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
